name: â˜ï¸ Release NPM

on:
  push:
    branches: main

jobs:
  npm:
    name: â˜ï¸ Release NPM
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v6

      - name: ğŸ› ï¸ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.18

      - name: âš¡ Install dependencies
        run: npm install

      - name: ğŸ”¨ Build library
        run: npm run build

      - name: â˜ï¸ Publish to NPM
        uses: JS-DevTools/npm-publish@v4.1.3
